version: "3.7"

volumes:
  postgres-data:

services:
  tempus:
    container_name: tempus
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    network_mode: host
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
#    ports:
#      - '5438:5432'
    volumes: 
      - postgres-data:/var/lib/postgresql/data
